# Generated by Django 4.2.21 on 2025-05-29 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store_app', '0002_alter_category_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name_plural': 'Product Categories'},
        ),
    ]
